apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false, Replace=true
    argocd.argoproj.io/sync-wave: "3"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: app-demo
spec:
  project: default
  source:
    repoURL: https://github.com/kirshiyin89/argocd-demo.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
